// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project0

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Pagina_Inicial
void ui_Pagina_Inicial_screen_init(void);
lv_obj_t * ui_Pagina_Inicial;
lv_obj_t * ui_Motor1;
lv_obj_t * ui_Motor2;
lv_obj_t * ui_Posicao1;
lv_obj_t * ui_Posicao2;
lv_obj_t * ui_Avanco1;
lv_obj_t * ui_Avanco2;
lv_obj_t * ui_Inversor1;
lv_obj_t * ui_Inversor2;
lv_obj_t * ui_Furo;
lv_obj_t * ui_LabelModoOperacao;
void ui_event_ButtonTelaManual(lv_event_t * e);
lv_obj_t * ui_ButtonTelaManual;
lv_obj_t * ui_Modo;
lv_obj_t * ui_Fileira;
lv_obj_t * ui_TempoEstimado;
lv_obj_t * ui_BrocaAtual;
lv_obj_t * ui_LabelFuradeira1;
lv_obj_t * ui_LabelFuradeira2;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container2;
void ui_event_ButtonTelaConfig(lv_event_t * e);
lv_obj_t * ui_ButtonTelaConfig;
void ui_event_Image6(lv_event_t * e);
lv_obj_t * ui_Image6;


// SCREEN: ui_Tela_de_Configuracao
void ui_Tela_de_Configuracao_screen_init(void);
lv_obj_t * ui_Tela_de_Configuracao;
lv_obj_t * ui_LabelInstrucoesEmergencia1;
void ui_event_ButtonTelaInicial(lv_event_t * e);
lv_obj_t * ui_ButtonTelaInicial;
lv_obj_t * ui_Image1;
lv_obj_t * ui_LabelAvanco;
lv_obj_t * ui_LabelRotacao;
lv_obj_t * ui_LabelProfundidade;
lv_obj_t * ui_LabelTamanho;
lv_obj_t * ui_LabelEspacamento;
lv_obj_t * ui_LabelFileiras;
lv_obj_t * ui_LabelFuros;
lv_obj_t * ui_ButtonSalvar1;
lv_obj_t * ui_LabelSalvar1;
lv_obj_t * ui_ButtonSalvar2;
lv_obj_t * ui_LabelSalvar2;
void ui_event_ButtonTesteEmergencia(lv_event_t * e);
lv_obj_t * ui_ButtonTesteEmergencia;
lv_obj_t * ui_LabelTesteEmergencia;
lv_obj_t * ui_LabelTelaConfiguracao;


// SCREEN: ui_Pagina_de_Controle_Manual
void ui_Pagina_de_Controle_Manual_screen_init(void);
lv_obj_t * ui_Pagina_de_Controle_Manual;
lv_obj_t * ui_FileiraAtual;
lv_obj_t * ui_LabelPosicaoAtual;
lv_obj_t * ui_FuroAtual;
lv_obj_t * ui_Container3;
lv_obj_t * ui_LabelPosicaoDestino;
lv_obj_t * ui_FuroDestino;
lv_obj_t * ui_FileiraDestino;
lv_obj_t * ui_ButtonRecolher1;
lv_obj_t * ui_ButtonRecolher2;
lv_obj_t * ui_LabelRecolher1;
lv_obj_t * ui_LabelRecolher2;
lv_obj_t * ui_LabelInstrucoes;
lv_obj_t * ui_Container4;
lv_obj_t * ui_LabelInstrucoes1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image8;
void ui_event_ButtonTelaInicial2(lv_event_t * e);
lv_obj_t * ui_ButtonTelaInicial2;
lv_obj_t * ui_LabelModoOperacao2;
lv_obj_t * ui_Modo2;


// SCREEN: ui_Pagina_de_Emergencia
void ui_Pagina_de_Emergencia_screen_init(void);
lv_obj_t * ui_Pagina_de_Emergencia;
lv_obj_t * ui_LabelEmergencia;
lv_obj_t * ui_LabelInstrucoesEmergencia;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonTelaManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Pagina_de_Controle_Manual, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0,
                          &ui_Pagina_de_Controle_Manual_screen_init);
        _ui_screen_delete(&ui_Pagina_Inicial);
    }
}
void ui_event_ButtonTelaConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Tela_de_Configuracao, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Tela_de_Configuracao_screen_init);
        _ui_screen_delete(&ui_Pagina_Inicial);
    }
}
void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Pagina_de_Controle_Manual, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0,
                          &ui_Pagina_de_Controle_Manual_screen_init);
    }
}
void ui_event_ButtonTelaInicial(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Pagina_Inicial, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pagina_Inicial_screen_init);
        _ui_screen_delete(&ui_Tela_de_Configuracao);
    }
}
void ui_event_ButtonTesteEmergencia(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Pagina_de_Emergencia, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pagina_de_Emergencia_screen_init);
        _ui_screen_delete(&ui_Tela_de_Configuracao);
    }
}
void ui_event_ButtonTelaInicial2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Pagina_Inicial, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Pagina_Inicial_screen_init);
        _ui_screen_delete(&ui_Pagina_de_Controle_Manual);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Pagina_Inicial_screen_init();
    ui_Tela_de_Configuracao_screen_init();
    ui_Pagina_de_Controle_Manual_screen_init();
    ui_Pagina_de_Emergencia_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Pagina_Inicial);
}
