// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project0

#include "ui.h"

void ui_Pagina_Inicial_screen_init(void)
{
    ui_Pagina_Inicial = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pagina_Inicial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pagina_Inicial, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pagina_Inicial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motor1 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Motor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Motor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Motor1, -200);
    lv_obj_set_y(ui_Motor1, 19);
    lv_obj_set_align(ui_Motor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Motor1, "Motor: [RPM]");
    lv_obj_set_style_text_font(ui_Motor1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motor2 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Motor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Motor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Motor2, 190);
    lv_obj_set_y(ui_Motor2, 17);
    lv_obj_set_align(ui_Motor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Motor2, "Motor: [RPM]");
    lv_obj_set_style_text_font(ui_Motor2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Posicao1 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Posicao1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Posicao1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Posicao1, -199);
    lv_obj_set_y(ui_Posicao1, 67);
    lv_obj_set_align(ui_Posicao1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Posicao1, "Posicao: [mm]");
    lv_obj_set_style_text_font(ui_Posicao1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Posicao2 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Posicao2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Posicao2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Posicao2, 190);
    lv_obj_set_y(ui_Posicao2, 63);
    lv_obj_set_align(ui_Posicao2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Posicao2, "Posicao: [mm]");
    lv_obj_set_style_text_font(ui_Posicao2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Avanco1 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Avanco1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Avanco1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Avanco1, -194);
    lv_obj_set_y(ui_Avanco1, 122);
    lv_obj_set_align(ui_Avanco1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Avanco1, "Avanco: [mm/s]");
    lv_obj_set_style_text_font(ui_Avanco1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Avanco2 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Avanco2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Avanco2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Avanco2, 193);
    lv_obj_set_y(ui_Avanco2, 116);
    lv_obj_set_align(ui_Avanco2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Avanco2, "Avanco: [mm/s]");
    lv_obj_set_style_text_font(ui_Avanco2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Inversor1 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Inversor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Inversor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Inversor1, -201);
    lv_obj_set_y(ui_Inversor1, 168);
    lv_obj_set_align(ui_Inversor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Inversor1, "Inversor: [A]");
    lv_obj_set_style_text_font(ui_Inversor1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Inversor2 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Inversor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Inversor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Inversor2, 188);
    lv_obj_set_y(ui_Inversor2, 167);
    lv_obj_set_align(ui_Inversor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Inversor2, "Inversor: [A]");
    lv_obj_set_style_text_font(ui_Inversor2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Furo = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Furo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Furo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Furo, 189);
    lv_obj_set_y(ui_Furo, -116);
    lv_obj_set_align(ui_Furo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Furo, "Contagem de Furos: ");
    lv_obj_set_style_text_align(ui_Furo, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Furo, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelModoOperacao = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_LabelModoOperacao, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModoOperacao, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModoOperacao, -144);
    lv_obj_set_y(ui_LabelModoOperacao, -206);
    lv_obj_set_align(ui_LabelModoOperacao, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModoOperacao, "Modo de Operacao:");
    lv_obj_set_style_text_font(ui_LabelModoOperacao, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTelaManual = lv_btn_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_ButtonTelaManual, 163);
    lv_obj_set_height(ui_ButtonTelaManual, 23);
    lv_obj_set_x(ui_ButtonTelaManual, 77);
    lv_obj_set_y(ui_ButtonTelaManual, -206);
    lv_obj_set_align(ui_ButtonTelaManual, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTelaManual, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTelaManual, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonTelaManual, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTelaManual, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTelaManual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonTelaManual, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonTelaManual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Modo = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Modo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Modo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Modo, 77);
    lv_obj_set_y(ui_Modo, -206);
    lv_obj_set_align(ui_Modo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Modo, "AUTOMATICO");
    lv_obj_set_style_text_font(ui_Modo, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Modo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Modo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Modo, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Modo, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fileira = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_Fileira, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fileira, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fileira, -198);
    lv_obj_set_y(ui_Fileira, -119);
    lv_obj_set_align(ui_Fileira, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fileira, "Fileira Atual: ");
    lv_obj_set_style_text_align(ui_Fileira, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fileira, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempoEstimado = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_TempoEstimado, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempoEstimado, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempoEstimado, 193);
    lv_obj_set_y(ui_TempoEstimado, -146);
    lv_obj_set_align(ui_TempoEstimado, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempoEstimado, "Tempo Restante Estimado: ");
    lv_obj_set_style_text_font(ui_TempoEstimado, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrocaAtual = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_BrocaAtual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrocaAtual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrocaAtual, -201);
    lv_obj_set_y(ui_BrocaAtual, -147);
    lv_obj_set_align(ui_BrocaAtual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrocaAtual, "Broca Atual:");
    lv_obj_set_style_text_font(ui_BrocaAtual, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuradeira1 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_LabelFuradeira1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuradeira1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuradeira1, -289);
    lv_obj_set_y(ui_LabelFuradeira1, -44);
    lv_obj_set_align(ui_LabelFuradeira1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFuradeira1, "Furadeira 1");
    lv_obj_set_style_text_font(ui_LabelFuradeira1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuradeira2 = lv_label_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_LabelFuradeira2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuradeira2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuradeira2, 102);
    lv_obj_set_y(ui_LabelFuradeira2, -44);
    lv_obj_set_align(ui_LabelFuradeira2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFuradeira2, "Furadeira 2");
    lv_obj_set_style_text_font(ui_LabelFuradeira2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Pagina_Inicial);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 359);
    lv_obj_set_height(ui_Container1, 289);
    lv_obj_set_x(ui_Container1, -195);
    lv_obj_set_y(ui_Container1, 75);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Pagina_Inicial);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 359);
    lv_obj_set_height(ui_Container2, 289);
    lv_obj_set_x(ui_Container2, 191);
    lv_obj_set_y(ui_Container2, 74);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTelaConfig = lv_btn_create(ui_Pagina_Inicial);
    lv_obj_set_width(ui_ButtonTelaConfig, 55);
    lv_obj_set_height(ui_ButtonTelaConfig, 50);
    lv_obj_set_x(ui_ButtonTelaConfig, -335);
    lv_obj_set_y(ui_ButtonTelaConfig, -155);
    lv_obj_set_align(ui_ButtonTelaConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTelaConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTelaConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonTelaConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTelaConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTelaConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonTelaConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonTelaConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Pagina_Inicial);
    lv_img_set_src(ui_Image6, &ui_img_cha_small_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 104
    lv_obj_set_x(ui_Image6, -330);
    lv_obj_set_y(ui_Image6, -163);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonTelaManual, ui_event_ButtonTelaManual, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTelaConfig, ui_event_ButtonTelaConfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);

}
