// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project0

#include "ui.h"

void ui_Tela_de_Configuracao_screen_init(void)
{
    ui_Tela_de_Configuracao = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tela_de_Configuracao, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tela_de_Configuracao, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tela_de_Configuracao, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInstrucoesEmergencia1 = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelInstrucoesEmergencia1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInstrucoesEmergencia1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInstrucoesEmergencia1, 1);
    lv_obj_set_y(ui_LabelInstrucoesEmergencia1, 32);
    lv_obj_set_align(ui_LabelInstrucoesEmergencia1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInstrucoesEmergencia1, "");
    lv_obj_set_style_text_font(ui_LabelInstrucoesEmergencia1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTelaInicial = lv_btn_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_ButtonTelaInicial, 55);
    lv_obj_set_height(ui_ButtonTelaInicial, 50);
    lv_obj_set_x(ui_ButtonTelaInicial, -328);
    lv_obj_set_y(ui_ButtonTelaInicial, -160);
    lv_obj_set_align(ui_ButtonTelaInicial, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTelaInicial, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTelaInicial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonTelaInicial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTelaInicial, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTelaInicial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonTelaInicial, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonTelaInicial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Tela_de_Configuracao);
    lv_img_set_src(ui_Image1, &ui_img_cha_small_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 104
    lv_obj_set_x(ui_Image1, -327);
    lv_obj_set_y(ui_Image1, -160);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAvanco = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelAvanco, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAvanco, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAvanco, -278);
    lv_obj_set_y(ui_LabelAvanco, -56);
    lv_obj_set_align(ui_LabelAvanco, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAvanco, "Avanco");
    lv_obj_set_style_text_font(ui_LabelAvanco, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRotacao = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelRotacao, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRotacao, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRotacao, -273);
    lv_obj_set_y(ui_LabelRotacao, -27);
    lv_obj_set_align(ui_LabelRotacao, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRotacao, "Rotacao");
    lv_obj_set_style_text_font(ui_LabelRotacao, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProfundidade = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelProfundidade, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProfundidade, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProfundidade, -242);
    lv_obj_set_y(ui_LabelProfundidade, 3);
    lv_obj_set_align(ui_LabelProfundidade, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProfundidade, "Profundidade");
    lv_obj_set_style_text_font(ui_LabelProfundidade, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTamanho = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelTamanho, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTamanho, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTamanho, -264);
    lv_obj_set_y(ui_LabelTamanho, 34);
    lv_obj_set_align(ui_LabelTamanho, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTamanho, "Tamanho");
    lv_obj_set_style_text_font(ui_LabelTamanho, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEspacamento = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelEspacamento, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEspacamento, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEspacamento, -244);
    lv_obj_set_y(ui_LabelEspacamento, 137);
    lv_obj_set_align(ui_LabelEspacamento, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEspacamento, "Espacamento");
    lv_obj_set_style_text_font(ui_LabelEspacamento, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFileiras = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelFileiras, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFileiras, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFileiras, -275);
    lv_obj_set_y(ui_LabelFileiras, 164);
    lv_obj_set_align(ui_LabelFileiras, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFileiras, "Fileiras");
    lv_obj_set_style_text_font(ui_LabelFileiras, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuros = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelFuros, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuros, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuros, -282);
    lv_obj_set_y(ui_LabelFuros, 193);
    lv_obj_set_align(ui_LabelFuros, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFuros, "Furos");
    lv_obj_set_style_text_font(ui_LabelFuros, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSalvar1 = lv_btn_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_ButtonSalvar1, 213);
    lv_obj_set_height(ui_ButtonSalvar1, 50);
    lv_obj_set_x(ui_ButtonSalvar1, 115);
    lv_obj_set_y(ui_ButtonSalvar1, 20);
    lv_obj_set_align(ui_ButtonSalvar1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSalvar1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSalvar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSalvar1 = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelSalvar1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSalvar1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSalvar1, 116);
    lv_obj_set_y(ui_LabelSalvar1, 21);
    lv_obj_set_align(ui_LabelSalvar1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSalvar1, "Salvar(not working)");
    lv_obj_set_style_text_font(ui_LabelSalvar1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSalvar2 = lv_btn_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_ButtonSalvar2, 213);
    lv_obj_set_height(ui_ButtonSalvar2, 50);
    lv_obj_set_x(ui_ButtonSalvar2, 115);
    lv_obj_set_y(ui_ButtonSalvar2, 165);
    lv_obj_set_align(ui_ButtonSalvar2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSalvar2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSalvar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSalvar2 = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelSalvar2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSalvar2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSalvar2, 118);
    lv_obj_set_y(ui_LabelSalvar2, 165);
    lv_obj_set_align(ui_LabelSalvar2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSalvar2, "Salvar(not working)");
    lv_obj_set_style_text_font(ui_LabelSalvar2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTesteEmergencia = lv_btn_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_ButtonTesteEmergencia, 213);
    lv_obj_set_height(ui_ButtonTesteEmergencia, 50);
    lv_obj_set_x(ui_ButtonTesteEmergencia, 121);
    lv_obj_set_y(ui_ButtonTesteEmergencia, -87);
    lv_obj_set_align(ui_ButtonTesteEmergencia, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTesteEmergencia, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTesteEmergencia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTesteEmergencia = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelTesteEmergencia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTesteEmergencia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTesteEmergencia, 112);
    lv_obj_set_y(ui_LabelTesteEmergencia, -85);
    lv_obj_set_align(ui_LabelTesteEmergencia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTesteEmergencia, "Teste Emergencia");
    lv_obj_set_style_text_font(ui_LabelTesteEmergencia, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTelaConfiguracao = lv_label_create(ui_Tela_de_Configuracao);
    lv_obj_set_width(ui_LabelTelaConfiguracao, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTelaConfiguracao, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTelaConfiguracao, 11);
    lv_obj_set_y(ui_LabelTelaConfiguracao, -199);
    lv_obj_set_align(ui_LabelTelaConfiguracao, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTelaConfiguracao, "Tela de Configuracao(Nao finalizada)");
    lv_obj_set_style_text_font(ui_LabelTelaConfiguracao, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonTelaInicial, ui_event_ButtonTelaInicial, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTesteEmergencia, ui_event_ButtonTesteEmergencia, LV_EVENT_ALL, NULL);

}
