// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project0

#ifndef _SQUARELINE_PROJECT0_UI_H
#define _SQUARELINE_PROJECT0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Pagina_Inicial
void ui_Pagina_Inicial_screen_init(void);
extern lv_obj_t * ui_Pagina_Inicial;
extern lv_obj_t * ui_Motor1;
extern lv_obj_t * ui_Motor2;
extern lv_obj_t * ui_Posicao1;
extern lv_obj_t * ui_Posicao2;
extern lv_obj_t * ui_Avanco1;
extern lv_obj_t * ui_Avanco2;
extern lv_obj_t * ui_Inversor1;
extern lv_obj_t * ui_Inversor2;
extern lv_obj_t * ui_Furo;
extern lv_obj_t * ui_LabelModoOperacao;
void ui_event_ButtonTelaManual(lv_event_t * e);
extern lv_obj_t * ui_ButtonTelaManual;
extern lv_obj_t * ui_Modo;
extern lv_obj_t * ui_Fileira;
extern lv_obj_t * ui_TempoEstimado;
extern lv_obj_t * ui_BrocaAtual;
extern lv_obj_t * ui_LabelFuradeira1;
extern lv_obj_t * ui_LabelFuradeira2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container2;
void ui_event_ButtonTelaConfig(lv_event_t * e);
extern lv_obj_t * ui_ButtonTelaConfig;
void ui_event_Image6(lv_event_t * e);
extern lv_obj_t * ui_Image6;
// SCREEN: ui_Tela_de_Configuracao
void ui_Tela_de_Configuracao_screen_init(void);
extern lv_obj_t * ui_Tela_de_Configuracao;
extern lv_obj_t * ui_LabelInstrucoesEmergencia1;
void ui_event_ButtonTelaInicial(lv_event_t * e);
extern lv_obj_t * ui_ButtonTelaInicial;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_LabelAvanco;
extern lv_obj_t * ui_LabelRotacao;
extern lv_obj_t * ui_LabelProfundidade;
extern lv_obj_t * ui_LabelTamanho;
extern lv_obj_t * ui_LabelEspacamento;
extern lv_obj_t * ui_LabelFileiras;
extern lv_obj_t * ui_LabelFuros;
extern lv_obj_t * ui_ButtonSalvar1;
extern lv_obj_t * ui_LabelSalvar1;
extern lv_obj_t * ui_ButtonSalvar2;
extern lv_obj_t * ui_LabelSalvar2;
void ui_event_ButtonTesteEmergencia(lv_event_t * e);
extern lv_obj_t * ui_ButtonTesteEmergencia;
extern lv_obj_t * ui_LabelTesteEmergencia;
extern lv_obj_t * ui_LabelTelaConfiguracao;
// SCREEN: ui_Pagina_de_Controle_Manual
void ui_Pagina_de_Controle_Manual_screen_init(void);
extern lv_obj_t * ui_Pagina_de_Controle_Manual;
extern lv_obj_t * ui_FileiraAtual;
extern lv_obj_t * ui_LabelPosicaoAtual;
extern lv_obj_t * ui_FuroAtual;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_LabelPosicaoDestino;
extern lv_obj_t * ui_FuroDestino;
extern lv_obj_t * ui_FileiraDestino;
extern lv_obj_t * ui_ButtonRecolher1;
extern lv_obj_t * ui_ButtonRecolher2;
extern lv_obj_t * ui_LabelRecolher1;
extern lv_obj_t * ui_LabelRecolher2;
extern lv_obj_t * ui_LabelInstrucoes;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_LabelInstrucoes1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image8;
void ui_event_ButtonTelaInicial2(lv_event_t * e);
extern lv_obj_t * ui_ButtonTelaInicial2;
extern lv_obj_t * ui_LabelModoOperacao2;
extern lv_obj_t * ui_Modo2;
// SCREEN: ui_Pagina_de_Emergencia
void ui_Pagina_de_Emergencia_screen_init(void);
extern lv_obj_t * ui_Pagina_de_Emergencia;
extern lv_obj_t * ui_LabelEmergencia;
extern lv_obj_t * ui_LabelInstrucoesEmergencia;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_cha_small_png);    // assets/cha_small.png
LV_IMG_DECLARE(ui_img_705276940);    // assets/output-onlinepngtools (3).png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
