// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project0

#include "ui.h"

void ui_Pagina_de_Controle_Manual_screen_init(void)
{
    ui_Pagina_de_Controle_Manual = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Pagina_de_Controle_Manual, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pagina_de_Controle_Manual, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pagina_de_Controle_Manual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FileiraAtual = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_FileiraAtual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FileiraAtual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FileiraAtual, -187);
    lv_obj_set_y(ui_FileiraAtual, -95);
    lv_obj_set_align(ui_FileiraAtual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FileiraAtual, "Fileira Atual: ");
    lv_obj_set_style_text_align(ui_FileiraAtual, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FileiraAtual, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosicaoAtual = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_LabelPosicaoAtual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosicaoAtual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosicaoAtual, -192);
    lv_obj_set_y(ui_LabelPosicaoAtual, -158);
    lv_obj_set_align(ui_LabelPosicaoAtual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPosicaoAtual, "Posicao Atual");
    lv_obj_set_style_text_font(ui_LabelPosicaoAtual, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPosicaoAtual, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPosicaoAtual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelPosicaoAtual, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelPosicaoAtual, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FuroAtual = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_FuroAtual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FuroAtual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuroAtual, -192);
    lv_obj_set_y(ui_FuroAtual, -120);
    lv_obj_set_align(ui_FuroAtual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FuroAtual, "Furo Atual:");
    lv_obj_set_style_text_font(ui_FuroAtual, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Pagina_de_Controle_Manual);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 344);
    lv_obj_set_height(ui_Container3, 289);
    lv_obj_set_x(ui_Container3, -192);
    lv_obj_set_y(ui_Container3, 73);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosicaoDestino = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_LabelPosicaoDestino, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosicaoDestino, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosicaoDestino, 168);
    lv_obj_set_y(ui_LabelPosicaoDestino, -156);
    lv_obj_set_align(ui_LabelPosicaoDestino, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPosicaoDestino, "Posicao Destino");
    lv_obj_set_style_text_font(ui_LabelPosicaoDestino, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPosicaoDestino, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPosicaoDestino, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelPosicaoDestino, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelPosicaoDestino, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FuroDestino = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_FuroDestino, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FuroDestino, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuroDestino, 172);
    lv_obj_set_y(ui_FuroDestino, -122);
    lv_obj_set_align(ui_FuroDestino, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FuroDestino, "Furo Destino:");
    lv_obj_set_style_text_font(ui_FuroDestino, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FileiraDestino = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_FileiraDestino, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FileiraDestino, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FileiraDestino, 174);
    lv_obj_set_y(ui_FileiraDestino, -98);
    lv_obj_set_align(ui_FileiraDestino, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FileiraDestino, "Fileira Destino: ");
    lv_obj_set_style_text_align(ui_FileiraDestino, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FileiraDestino, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRecolher1 = lv_btn_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_ButtonRecolher1, 258);
    lv_obj_set_height(ui_ButtonRecolher1, 50);
    lv_obj_set_x(ui_ButtonRecolher1, 182);
    lv_obj_set_y(ui_ButtonRecolher1, 48);
    lv_obj_set_align(ui_ButtonRecolher1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonRecolher1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonRecolher1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ButtonRecolher1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRecolher1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonRecolher2 = lv_btn_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_ButtonRecolher2, 258);
    lv_obj_set_height(ui_ButtonRecolher2, 50);
    lv_obj_set_x(ui_ButtonRecolher2, 182);
    lv_obj_set_y(ui_ButtonRecolher2, 130);
    lv_obj_set_align(ui_ButtonRecolher2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonRecolher2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonRecolher2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ButtonRecolher2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRecolher2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelRecolher1 = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_LabelRecolher1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRecolher1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRecolher1, 180);
    lv_obj_set_y(ui_LabelRecolher1, 48);
    lv_obj_set_align(ui_LabelRecolher1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRecolher1, "Recolher Furadeira 1");
    lv_obj_set_style_text_align(ui_LabelRecolher1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRecolher1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRecolher2 = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_LabelRecolher2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRecolher2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRecolher2, 180);
    lv_obj_set_y(ui_LabelRecolher2, 130);
    lv_obj_set_align(ui_LabelRecolher2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRecolher2, "Recolher Furadeira 2");
    lv_obj_set_style_text_align(ui_LabelRecolher2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRecolher2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInstrucoes = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_LabelInstrucoes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInstrucoes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInstrucoes, -188);
    lv_obj_set_y(ui_LabelInstrucoes, -17);
    lv_obj_set_align(ui_LabelInstrucoes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInstrucoes, "Selecione o Furo destino com o\n controlador Joystick\n");
    lv_obj_set_style_text_align(ui_LabelInstrucoes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelInstrucoes, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Pagina_de_Controle_Manual);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 344);
    lv_obj_set_height(ui_Container4, 289);
    lv_obj_set_x(ui_Container4, 188);
    lv_obj_set_y(ui_Container4, 72);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInstrucoes1 = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_LabelInstrucoes1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInstrucoes1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInstrucoes1, 184);
    lv_obj_set_y(ui_LabelInstrucoes1, -37);
    lv_obj_set_align(ui_LabelInstrucoes1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInstrucoes1, "Pressione para recolher a furadeira \npara o ponto inicial (home)");
    lv_obj_set_style_text_align(ui_LabelInstrucoes1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelInstrucoes1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Pagina_de_Controle_Manual);
    lv_img_set_src(ui_Image2, &ui_img_cha_small_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 104
    lv_obj_set_x(ui_Image2, -330);
    lv_obj_set_y(ui_Image2, -163);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Pagina_de_Controle_Manual);
    lv_img_set_src(ui_Image8, &ui_img_705276940);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 140
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 140
    lv_obj_set_x(ui_Image8, -193);
    lv_obj_set_y(ui_Image8, 97);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonTelaInicial2 = lv_btn_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_ButtonTelaInicial2, 104);
    lv_obj_set_height(ui_ButtonTelaInicial2, 23);
    lv_obj_set_x(ui_ButtonTelaInicial2, 62);
    lv_obj_set_y(ui_ButtonTelaInicial2, -205);
    lv_obj_set_align(ui_ButtonTelaInicial2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTelaInicial2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTelaInicial2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonTelaInicial2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTelaInicial2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTelaInicial2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonTelaInicial2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonTelaInicial2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelModoOperacao2 = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_LabelModoOperacao2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModoOperacao2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModoOperacao2, -147);
    lv_obj_set_y(ui_LabelModoOperacao2, -206);
    lv_obj_set_align(ui_LabelModoOperacao2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModoOperacao2, "Modo de Operacao:");
    lv_obj_set_style_text_font(ui_LabelModoOperacao2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Modo2 = lv_label_create(ui_Pagina_de_Controle_Manual);
    lv_obj_set_width(ui_Modo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Modo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Modo2, 62);
    lv_obj_set_y(ui_Modo2, -206);
    lv_obj_set_align(ui_Modo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Modo2, "MANUAL");
    lv_obj_set_style_text_font(ui_Modo2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Modo2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Modo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Modo2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Modo2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonTelaInicial2, ui_event_ButtonTelaInicial2, LV_EVENT_ALL, NULL);

}
